name = "nossalojaaqui-site"
main = "worker.js"
compatibility_date = "2026-08-23"

[assets]
directory = "./site"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "nossalojaaqui"
database_id = "472d7155-7a86-465b-88a3-92bcc69c9495"
[[routes]]
pattern = "catalogo.nossalojaaqui.com.br"
custom_domain = true
